spring:
  #db
  datasource:
    url: jdbc:mariadb://mjgolf.myqnapcloud.com:3306/emp
    username: suk
    password: ghdtjr2@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  # 멀티파트 요청 처리
  # 파일 업로드 최대 크기 10MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.example.test.emp

  #카멜 케이스
#  configuration:
#    map-underscore-to-camel-case: true