spring:
  #db
  datasource:
    url: jdbc:mariadb://mjgolf.myqnapcloud.com:3306/emp
    username: suk
    password: ghdtjr2@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    cors:
      # 프론트엔드 도메인(Origin)을 허용합니다.
      allowed-origins: http://localhost:3000
      # 허용할 HTTP 메서드를 지정합니다.
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      # 허용할 HTTP 헤더를 지정합니다.
      allowed-headers: Origin, Content-Type, Accept, Authorization
      # "Access-Control-Allow-Credentials" 헤더를 허용할지 여부를 지정합니다.
      allow-credentials: true


  # 멀티파트 요청 처리
  # 파일 업로드 최대 크기 10MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # message properties
  messages:
    basename: messages
    encoding: UTF-8
    # 기본 로케일(정의된 문자열)에서만 메시지를 검색할지 여부
    fallback-to-system-locale: false
    # 메시지를 항상 포맷 문자열로 처리
    always-use-message-format: true
    # 캐싱하지 않도록
    #cache-duration: 3 # 3초간 만 캐싱


mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.example.test.api

  #카멜 케이스
#  configuration:
#    map-underscore-to-camel-case: true